[project]
name = "ml-lab1"
version = "0.1.0"
description = "Machine learning lab 1"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.3",
    "openpyxl>=3.1.5",
    "pandas>=2.3.2",
    "scikit-learn>=1.7.2",
]
